### ISSUE TITLE
Bullet and Number size not changing with Font Size

### ISSUE THREAD

**Issue by satyadeeproat** [zenoamaro/react-quill#114]
Hi,
I am using numbering part for the editor but the size of number remain same even if I increase the font size to Huge.

**Comment by alexkrolick** [comment]
Please address this upstream with the underlying editor, Quill. The issue may have been fixed in the upcoming 1.0.0 release.

https://github.com/quilljs/quill

**Comment by Surendranath26** [comment]
Issue still exist on the    "quill": "^1.3.7"  version of quillJS. so open this issue again.

**Comment by Sajad321** [comment]
This issue still exist in 2.0.0
